import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import './theme-config.css';
import '@radix-ui/themes/styles.css';
import Navbar from './Navbar';
import { Theme, ThemePanel } from '@radix-ui/themes';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${inter.variable} antialiased`}>
        <Theme accentColor='gold' radius='large' appearance='dark'>
          <Navbar />
          <main className='p-6'>{children}</main>
        </Theme>
      </body>
    </html>
  );
}
